### ISSUE TITLE
what driver is responsible for mmcblk devices?

### ISSUE THREAD

**Issue by chayleaf** [nakato/nixos-bpir3-example#2]
I'm trying to boot NixOS on BPI-R3, [here's my config](https://github.com/chayleaf/dotfiles/tree/a96bd4bbcd6e465789fedeb438d78f2099c40d21/system/hosts/router) and [packages](https://github.com/chayleaf/dotfiles/tree/a96bd4bbcd6e465789fedeb438d78f2099c40d21/pkgs). It mostly works, but doesn't boot because `/dev/mmcblk0` doesn't appear. I assume that's because I'm using the default kernel (`linux_testing`), [I saw someone else using it](https://github.com/jmbaur/homelab/commit/02648e9a349528d87dd57a0caec8043927eaf306) so I figured it'd be fine.

Do you have any ideas why the device isn't appearing? I made sure `mmc_block` kernel module is loaded. Comparing dmesg logs, my logs lack `mtk-pcie` output, but I'm not sure what to do with this info. Do I have to compile a custom kernel, or can I use the default one?

**Comment by nakato** [comment]
> I saw someone else using it so I figured it'd be fine.

I don't see how the example "homelab" configuration could be functional.  It is applying all four of the  devicetree overlays.  The NOR and NAND ones and the SD, and eMMC overlays are mutually exclusive due to the wiring of the BPi-R3.

> here's my config

I might have missed it, but I don't see any devicetree overlays being applied in your config; for the storage device to be detected, you'll need to apply the appropriate devicetree overlay for your backing storage at build time.

For SD based boot, the following.  Though this repo chooses to use a local copy of said file.
```nix
{config, ...}: {
  hardware.deviceTree.overlays = [
      {
        name = "mt7986a-bananapi-bpi-r3-sd.dtbo";
        dtboFile = "${config.boot.kernelPackages.kernel}/dtbs/mediatek/mt7986a-bananapi-bpi-r3-sd.dtbo";
      }
  ];
}
```

Module wise, it's `mtk-sd`.

> Do I have to compile a custom kernel, or can I use the default one?

I suspect you can get the device to boot without a custom kernel, but I expect none of the ethernet ports will be functional.  I had to compile in `kernel/drivers/net/ethernet/mediatek/mtk_eth.ko` and `kernel/net/dsa/tag_mtk.ko`.
Someone reported this upstream, but it looks like they didn't follow up on the response; see https://lore.kernel.org/all/ZA0qBQJRt4ZZpV2J@uejikov.net/

There's similar issues with `kernel/drivers/pci/controller/pcie-mediatek-gen3.ko` as well IIRC.

**Comment by chayleaf** [comment]
Thanks, I confused dtb and dtbo files so I thought setting `deviceTree.filter` would be enough.

Ethernet didn't work (I did use a custom kernel after all, but mtk_eth wasn't compiled in), so I'll rebuild the kernel and try again.
